services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: aury
      POSTGRES_PASSWORD: aury
      POSTGRES_DB: aury3
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
